### ISSUE TITLE
Support `msgpack` format as `to_td` option

### ISSUE THREAD

**Issue by akito19** [treasure-data/pytd#78] opened 2020-03-19 12:29 UTC
### Purpose

Import `object` datatype values of DataFrame to Treasure Data as `string` type.

### Behaviors

Currently, when we try to import these data into Treasure Data by using `pandas_td.to_td`, the values would be not necessarily that these are `object`:

e.g.)

```py
import pytd.pandas_td as td
import pandas as pd

df = pd.DataFrame([{'id':'00123', 'num': '45678'}])
con = td.connect()

td.to_td(df, 'kasai_test.pytd', con, if_exists='replace')
```

In this case, both `id` and `num` are stored as `long` type in Treasure Data in spite of `object` type in DataFrame.
I guess that converting to CSV might cause this result since CSV doesn't have typing system.

However, `fmt='msgpack'` has been available in calling `BulkImportWriter.write_dataframe` since version [1.0.0](https://github.com/treasure-data/pytd/blob/master/CHANGELOG.rst#v100-2019-11-11).
Thus, we can store these values as `string` if we use the `write_dataframe` explicitly like below:

```py
import pytd
import pandas as pd

df = pd.DataFrame({'id': '00324', 'test': '5678'}, index=range(2))
client = pytd.Client()

table = pytd.table.Table(client, "kasai_test", "pytd")
writer = pytd.writer.BulkImportWriter()
writer.write_dataframe(df, table, if_exists="overwrite", fmt="msgpack")
```

Because pytd has already enabled choosing format when using `bulk_import`, users might expect to be able to set format as well as `write_dataframe`.
Thus, I propose that pytd supports `msgpack` format in `to_td` options.

What do you think about it?

**Comment by chezou** [comment] 2020-03-27 03:39
@akito19 Thanks for raising the issue. We also faced the same issue with td-client-python and the cause was reading CSV for bulk import may break type information for 0-padded number conversion.
https://github.com/treasure-data/td-client-python/issues/83

I think there are two options to deal with the issue:

1. Support `fmt="msgpack"` to `to_td` option. This should be an easy fix for the issue.
2. Make `fmt="msgpack"` as default rather than `fmt="csv"`. 

For option 2, although this would introduce type inconsistency i.e., `"00012"` was ingested as integer `12` with CSV format, but will be ingested as `"00012"`, I think this behavior should be unintentional and this is against to [the principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by chezou** [comment] 2020-03-30 02:13
@akito19 We merged #80 which allows passing `fmt="msgpack"` as an argument of `to_td` function. Could you try master branch? Detailed usage is written in the PR #80.

@takuti How do you feel to make `fmt="msgpack"` is default instead of CSV?

**Comment by akito19** [comment] 2020-03-30 02:44
@chezou Thank you for the update!
I confirmed `fmt="msgpack"` was available in `to_td` fuction.

```
>>> import pytd.pandas_td as td
>>> import pandas as pd
>>> df = pd.DataFrame([{'id':'00123', 'num': '45678'}])
>>> client = pytd.Client(apikey='10452/7649e08ae0fbb575a723cf91fb85b0e5997f4d8f', endpoint='https://api.treasuredata.com/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pytd' is not defined
>>> client = td.Client()
>>> td.to_td(df, 'kasai_test.pytd', client, if_exists='replace', fmt='msgpack')
uploading data converted into a msgpack file
performing a bulk import job
[job id 708942835] imported 1 records.
```

**Comment by takuti** [comment] 2020-03-31 03:03
@chezou Let's first improve documentation of `fmt` option e.g., describing the known issue of using `fmt="csv"` in:
https://github.com/treasure-data/pytd/blob/8d9a79f74673b923554c3298d6b77b55669cd785/pytd/writer.py#L336-L345

Plus, simply copying-n-pasting docstrings of `fmt` and `keep_list` options to `pytd.pandas_td.to_td` and `pytd.Table.import_dataframe` would be helpful for users' reference.

When we become able to say `fmt="msgpack"` is stable enough, that'd be the time to change default `fmt` to `msgpack`. We improved MessagePack handling a lot lately, so do you think the file format is safe enough?

**Comment by chezou** [comment] 2020-03-31 04:36
@takuti Agreed to add docstring and README.rst.

pandas 1.0 support improves `fmt="msgpack"` type conversion stability a lot, and the only difference I can come out with is 0-pad string handling, and that is unintended behavior. But, I'm ok to wait a certain time after updating the doc for `to_td`.

**Comment by chezou** [comment] 2020-04-01 01:15
We now updated [the document](https://pytd-doc.readthedocs.io/en/latest/#how-to-replace-pandas-td) and supported `fmt` option on "to_td" function.  Will create another issue for making `fmt="msgpack"` default option.

**Closed by chezou** 2020-04-01 01:15 UTC
